### PR TITLE
Add /statedump endpoint for metrics

### LINKED ISSUE #218: GD2 statedump support (possibly a ReST endpoint)
Just like we have statedump support in GD1, a similar mechanism needs to be built in GD2.

### PR DESCRIPTION
**Pull request by prashanthpai**
Closes #218

### CODE REVIEW

**Comment by prashanthpai** [comment]
```sh
$ curl -s -X GET http://localhost.localdomain:24007/statedump | python -m json.tool
{
    "cmdline": [
        "glusterd2",
        "--config",
        "1.yaml"
    ],
    "file_descriptor_limit": 1024,
    "http_client_errors": 1,
    "http_server_errors": 1,
    "http_success_responses": 2,
    "http_total_requests_received": 4,
    "initiated_txns_in_progress": 0,
    "memstats": {
        "Alloc": 5007528,
        "BuckHashSys": 1494718,
        "BySize": [
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 0
            },
            {
                "Frees": 16492,
                "Mallocs": 17023,
                "Size": 8
            },
            {
                "Frees": 35055,
                "Mallocs": 42273,
                "Size": 16
            },
            {
                "Frees": 17630,
                "Mallocs": 28875,
                "Size": 32
            },
            {
                "Frees": 33596,
                "Mallocs": 36227,
                "Size": 48
            },
            {
                "Frees": 33299,
                "Mallocs": 36939,
                "Size": 64
            },
            {
                "Frees": 382,
                "Mallocs": 1140,
                "Size": 80
            },
            {
                "Frees": 157,
                "Mallocs": 1617,
                "Size": 96
            },
            {
                "Frees": 16915,
                "Mallocs": 17732,
                "Size": 112
            },
            {
                "Frees": 122,
                "Mallocs": 386,
                "Size": 128
            },
            {
                "Frees": 40,
                "Mallocs": 267,
                "Size": 144
            },
            {
                "Frees": 62,
                "Mallocs": 305,
                "Size": 160
            },
            {
                "Frees": 28,
                "Mallocs": 198,
                "Size": 176
            },
            {
                "Frees": 95,
                "Mallocs": 157,
                "Size": 192
            },
            {
                "Frees": 315,
                "Mallocs": 616,
                "Size": 208
            },
            {
                "Frees": 13,
                "Mallocs": 657,
                "Size": 224
            },
            {
                "Frees": 1,
                "Mallocs": 54,
                "Size": 240
            },
            {
                "Frees": 33,
                "Mallocs": 146,
                "Size": 256
            },
            {
                "Frees": 79,
                "Mallocs": 254,
                "Size": 288
            },
            {
                "Frees": 34,
                "Mallocs": 141,
                "Size": 320
            },
            {
                "Frees": 27,
                "Mallocs": 120,
                "Size": 352
            },
            {
                "Frees": 51,
                "Mallocs": 73,
                "Size": 384
            },
            {
                "Frees": 15,
                "Mallocs": 173,
                "Size": 416
            },
            {
                "Frees": 15,
                "Mallocs": 43,
                "Size": 448
            },
            {
                "Frees": 5,
                "Mallocs": 23,
                "Size": 480
            },
            {
                "Frees": 30,
                "Mallocs": 77,
                "Size": 512
            },
            {
                "Frees": 23,
                "Mallocs": 42,
                "Size": 576
            },
            {
                "Frees": 25,
                "Mallocs": 65,
                "Size": 640
            },
            {
                "Frees": 6,
                "Mallocs": 21,
                "Size": 704
            },
            {
                "Frees": 38,
                "Mallocs": 55,
                "Size": 768
            },
            {
                "Frees": 13,
                "Mallocs": 28,
                "Size": 896
            },
            {
                "Frees": 12,
                "Mallocs": 66,
                "Size": 1024
            },
            {
                "Frees": 21,
                "Mallocs": 31,
                "Size": 1152
            },
            {
                "Frees": 10,
                "Mallocs": 32,
                "Size": 1280
            },
            {
                "Frees": 2,
                "Mallocs": 4,
                "Size": 1408
            },
            {
                "Frees": 31,
                "Mallocs": 45,
                "Size": 1536
            },
            {
                "Frees": 31,
                "Mallocs": 54,
                "Size": 1792
            },
            {
                "Frees": 2,
                "Mallocs": 49,
                "Size": 2048
            },
            {
                "Frees": 3,
                "Mallocs": 16,
                "Size": 2304
            },
            {
                "Frees": 4,
                "Mallocs": 13,
                "Size": 2688
            },
            {
                "Frees": 16,
                "Mallocs": 24,
                "Size": 3072
            },
            {
                "Frees": 0,
                "Mallocs": 2,
                "Size": 3200
            },
            {
                "Frees": 0,
                "Mallocs": 7,
                "Size": 3456
            },
            {
                "Frees": 47,
                "Mallocs": 93,
                "Size": 4096
            },
            {
                "Frees": 5,
                "Mallocs": 12,
                "Size": 4864
            },
            {
                "Frees": 0,
                "Mallocs": 5,
                "Size": 5376
            },
            {
                "Frees": 8,
                "Mallocs": 23,
                "Size": 6144
            },
            {
                "Frees": 0,
                "Mallocs": 5,
                "Size": 6528
            },
            {
                "Frees": 0,
                "Mallocs": 1,
                "Size": 6784
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 6912
            },
            {
                "Frees": 0,
                "Mallocs": 5,
                "Size": 8192
            },
            {
                "Frees": 0,
                "Mallocs": 2,
                "Size": 9472
            },
            {
                "Frees": 1,
                "Mallocs": 1,
                "Size": 9728
            },
            {
                "Frees": 1,
                "Mallocs": 1,
                "Size": 10240
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 10880
            },
            {
                "Frees": 0,
                "Mallocs": 23,
                "Size": 12288
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 13568
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 14336
            },
            {
                "Frees": 0,
                "Mallocs": 4,
                "Size": 16384
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 18432
            },
            {
                "Frees": 0,
                "Mallocs": 0,
                "Size": 19072
            }
        ],
        "DebugGC": false,
        "EnableGC": true,
        "Frees": 174400,
        "GCCPUFraction": 0.010943083021873334,
        "GCSys": 440320,
        "HeapAlloc": 5007528,
        "HeapIdle": 131072,
        "HeapInuse": 5603328,
        "HeapObjects": 31483,
        "HeapReleased": 0,
        "HeapSys": 5734400,
        "LastGC": 1507654376594594926,
        "Lookups": 33050,
        "MCacheInuse": 2400,
        "MCacheSys": 16384,
        "MSpanInuse": 63232,
        "MSpanSys": 98304,
        "Mallocs": 205883,
        "NextGC": 5739936,
        "NumForcedGC": 0,
        "NumGC": 4,
        "OtherSys": 651834,
        "PauseEnd": [
            1507654376373837703,
            1507654376494031084,
            1507654376591089233,
            1507654376594594926,
            0,
            ....
        ],
        "PauseNs": [
            151365,
            74260,
            318902,
            118236,
            0,
            0,
            ......
        ],
        "PauseTotalNs": 662763,
        "StackInuse": 753664,
        "StackSys": 753664,
        "Sys": 9189624,
        "TotalAlloc": 14422792
    },
    "pmap_last_allocated_port": 0,
    "raft.status": {
        "commit": 109,
        "id": "11bff47b8baf3ee9",
        "lead": "11bff47b8baf3ee9",
        "progress": {
            "11bff47b8baf3ee9": {
                "match": 109,
                "next": 110,
                "state": "ProgressStateProbe"
            }
        },
        "raftState": "StateLeader",
        "term": 10,
        "vote": "11bff47b8baf3ee9"
    },
    "sunrpc_clients_connected": 0
}
```

**Comment by prashanthpai** [comment]
TODO:
As suggested by @atinmu , add support for dumping statedump to a file.

**Comment by prashanthpai** [comment]
Statedumps can be queried using REST API and also it can be dumped to file by sending `SIGUSR1` signal:

```sh
$ curl -s -X GET http://127.0.0.1:24007/statedump
```

OR

```sh
$ sudo kill -SIGUSR1 `pgrep glusterd2`
```

Statedump:

```json
{
"cmdline": ["glusterd2","--config","1.yaml"],
"config": {"cert-file": , "clientaddress": :24007, "config": 1.yaml, "defaultpeerport": 24008, "etcdcurls": http://127.0.0.1:2479, "etcdendpoints": , "etcdpurls": http://127.0.0.1:2480, "key-file": , "localstatedir": /tmp/gd2_func_test/w1, "logdir": /tmp/gd2_func_test/w1/log, "logfile": w1.log, "loglevel": debug, "mgmt": false, "no-embed": false, "peeraddress": 127.0.0.1:24008, "rundir": /tmp/gd2_func_test/w1/run, "statedump": true, "templatesdir": /usr/local/share/glusterd2/templates, "version": false, "workdir": /tmp/gd2_func_test/w1},
"file_descriptor_limit": 1024,
"http_client_errors": 2,
"http_in_progress_requests": 0,
"http_server_errors": 0,
"http_success_responses": 6,
"http_total_requests_received": 8,
"initiated_txns_in_progress": 0,
"op_version": 40000,
"pmap_last_allocated_port": 0,
"sunrpc_clients_connected": 0,
"uuid": "df65b5f6-f79f-41d3-bab9-600fcb1263aa",
"version": "v4.0dev-7.118.gitf1bd9b4"
}
"raft.status": {"id":"11bff47b8baf3ee9","term":3,"vote":"11bff47b8baf3ee9","commit":19,"lead":"11bff47b8baf3ee9","raftState":"StateLeader","progress":{"11bff47b8baf3ee9":{"match":19,"next":20,"state":"ProgressStateProbe"}}},
"memstats": {"Alloc":4160264,"TotalAlloc":21786048,"Sys":10270968,"Lookups":33474,"Mallocs":304909,"Frees":280033,"HeapAlloc":4160264,"HeapSys":6717440,"HeapIdle":1671168,"HeapInuse":5046272,"HeapReleased":974848,"HeapObjects":24876,"StackInuse":819200,"StackSys":819200,"MSpanInuse":59128,"MSpanSys":98304,"MCacheInuse":2400,"MCacheSys":16384,"BuckHashSys":1496279,"GCSys":471040,"OtherSys":652321,"NextGC":6988992,"LastGC":1507722500488057396,"PauseTotalNs":4722671,"PauseNs":[150199,395809,129740,984792,308723,98530,1655434,275868,126156,597420,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1507721808670134101,1507721808877075385,1507721809047993386,1507721809755879592,1507721900364878163,1507722020383259220,1507722140396722324,1507722260426615981,1507722380456836306,1507722500488057396,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":10,"NumForcedGC":0,"GCCPUFraction":0.0000566737374230412,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":17432,"Frees":17129},{"Size":16,"Mallocs":68096,"Frees":62730},{"Size":32,"Mallocs":45100,"Frees":34687},{"Size":48,"Mallocs":39397,"Frees":37557},{"Size":64,"Mallocs":57788,"Frees":55437},{"Size":80,"Mallocs":1499,"Frees":968},{"Size":96,"Mallocs":12986,"Frees":11816},{"Size":112,"Mallocs":18635,"Frees":18160},{"Size":128,"Mallocs":1879,"Frees":1684},{"Size":144,"Mallocs":263,"Frees":91},{"Size":160,"Mallocs":319,"Frees":158},{"Size":176,"Mallocs":157,"Frees":74},{"Size":192,"Mallocs":160,"Frees":93},{"Size":208,"Mallocs":3574,"Frees":3289},{"Size":224,"Mallocs":7394,"Frees":6917},{"Size":240,"Mallocs":103,"Frees":66},{"Size":256,"Mallocs":165,"Frees":82},{"Size":288,"Mallocs":295,"Frees":206},{"Size":320,"Mallocs":373,"Frees":282},{"Size":352,"Mallocs":206,"Frees":133},{"Size":384,"Mallocs":67,"Frees":50},{"Size":416,"Mallocs":199,"Frees":19},{"Size":448,"Mallocs":28,"Frees":20},{"Size":480,"Mallocs":17,"Frees":9},{"Size":512,"Mallocs":64,"Frees":45},{"Size":576,"Mallocs":59,"Frees":47},{"Size":640,"Mallocs":65,"Frees":42},{"Size":704,"Mallocs":31,"Frees":22},{"Size":768,"Mallocs":51,"Frees":36},{"Size":896,"Mallocs":29,"Frees":16},{"Size":1024,"Mallocs":69,"Frees":24},{"Size":1152,"Mallocs":36,"Frees":27},{"Size":1280,"Mallocs":34,"Frees":12},{"Size":1408,"Mallocs":10,"Frees":7},{"Size":1536,"Mallocs":41,"Frees":29},{"Size":1792,"Mallocs":239,"Frees":218},{"Size":2048,"Mallocs":52,"Frees":5},{"Size":2304,"Mallocs":18,"Frees":8},{"Size":2688,"Mallocs":17,"Frees":4},{"Size":3072,"Mallocs":22,"Frees":14},{"Size":3200,"Mallocs":2,"Frees":0},{"Size":3456,"Mallocs":7,"Frees":0},{"Size":4096,"Mallocs":299,"Frees":264},{"Size":4864,"Mallocs":16,"Frees":12},{"Size":5376,"Mallocs":5,"Frees":0},{"Size":6144,"Mallocs":26,"Frees":14},{"Size":6528,"Mallocs":5,"Frees":1},{"Size":6784,"Mallocs":2,"Frees":1},{"Size":6912,"Mallocs":2,"Frees":2},{"Size":8192,"Mallocs":7,"Frees":3},{"Size":9472,"Mallocs":2,"Frees":0},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":1,"Frees":1},{"Size":10880,"Mallocs":0,"Frees":0},{"Size":12288,"Mallocs":23,"Frees":0},{"Size":13568,"Mallocs":0,"Frees":0},{"Size":14336,"Mallocs":0,"Frees":0},{"Size":16384,"Mallocs":4,"Frees":0},{"Size":18432,"Mallocs":0,"Frees":0},{"Size":19072,"Mallocs":0,"Frees":0}]},
```

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
> Shouldn't we also add the portmap details?

@atinmu Done. I've updated the sample output in the comment above.

**Comment by prashanthpai** [comment]
retest this please

**Comment by atinmu** [comment]
retest this please

**Pull request merged**
