### PR TITLE
Fix error message

### PR DESCRIPTION
**Pull request by Madhu-1**
error messages should start with small case.

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by rishubhjain** [comment]
CI error, self heal is failing in this PR as well.

**Comment by aravindavk** [comment]
retest this please

**Comment by aravindavk** [comment]
retest this please

**Comment by aravindavk** [comment]
Retriggered tests because of glusterd2 restart failure

```
20:34:31 --- FAIL: TestBrickMux (23.19s)
20:34:31 	process_utils_test.go:112: IsRestServerUp(): Get failed: Get http://127.0.0.1:24007/v1/peers: dial tcp 127.0.0.1:24007: getsockopt: connection refused
20:34:31 	process_utils_test.go:112: IsRestServerUp(): Get failed: Get http://127.0.0.1:24007/v1/peers: dial tcp 127.0.0.1:24007: getsockopt: connection refused
20:34:31 	process_utils_test.go:112: IsRestServerUp(): Get failed: Get http://127.0.0.1:24007/v1/peers: dial tcp 127.0.0.1:24007: getsockopt: connection refused
20:34:31 	process_utils_test.go:112: IsRestServerUp(): Get failed: Get http://127.0.0.1:24007/v1/peers: dial tcp 127.0.0.1:24007: getsockopt: connection refused
20:34:31 	process_utils_test.go:112: IsRestServerUp(): Get failed: Get http://127.0.0.1:24007/v1/peers: dial tcp 127.0.0.1:24007: getsockopt: connection refused
20:34:31 	require.go:765: 
20:34:31 			Error Trace:	brickmux_test.go:256
20:34:31 			Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query gd2 () rest server"}
20:34:31 			Test:       	TestBrickMux
```

**Pull request merged**
