### PR TITLE
Fix golint warnings

### PR DESCRIPTION
**Pull request by prashanthpai**
Barring transaction subpackage which contains mainly generated code,
other subpackages have had their golint warnings fixed.

We would want to ensure that all new code adheres to golint.

Signed-off-by: Prashanth Pai ppai@redhat.com

### CODE REVIEW

**Comment by purpleidea** [comment]
> We would want to ensure that all new code adheres to golint.

You probably want to make sure that all code adheres to `go vet`. Golint is *usually* right, but not always!

**Comment by kshlm** [comment]
@purpleidea, we're using gometalinter, which runs a bunch of stuff, including golint and go vet.

**Comment by kshlm** [comment]
@purpleidea, we're using gometalinter, which runs a bunch of stuff, including golint and go vet.

**Comment by kshlm** [comment]
@purpleidea, we're using gometalinter, which runs a bunch of stuff, including golint and go vet.

**Comment by prashanthpai** [comment]
@kshlm Rebased to master. Consider merging this.

**Pull request merged**
