### PR TITLE
Use glusterfs binary to mount

### PR DESCRIPTION
**Pull request by prashanthpai**
..as `mount.glusterfs` utility might be installed in non-standard
location in test environments.

Besides, mounts in real code (volume status) already uses the binary
to mount and not the mount utility script.

Signed-off-by: Prashanth Pai <ppai@redhat.com>

### CODE REVIEW

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
Unlike invoking `mount.glusterfs` as a command, `glusterfs` daemonizes itself. Will update this PR later with that fix.

**Comment by amarts** [comment]
> Unlike invoking mount.glusterfs as a command, glusterfs daemonizes itself. Will update this PR later with that fix. 

Didn't understand what you are trying to say. Are you saying daemonizing doesn't work ? then recommend using `-N` option.

**Comment by prashanthpai** [comment]
> Didn't understand what you are trying to say. Are you saying daemonizing doesn't work ? then recommend using -N option.

In go, `exec.Command.Run` starts the specified command and waits for it to complete. As glusterfs mount will be a daemon, we just had to use [exec.Command.Start](https://golang.org/pkg/os/exec/#Cmd.Start) instead.

> Was just thinking. While at it, can we at least run one more command on mount? Like 'touch' or at least stat ?

 :+1:

**Pull request merged**
