### PR TITLE
volgen: Include Option default values in volfiles

### PR DESCRIPTION
**Pull request by aravindavk**
If default value in xlators option table is not empty then
it will be added in volfiles.

Also added `afr-pending-xattr` option to client volfile.

Fixes: #890
Signed-off-by: Aravinda VK <avishwan@redhat.com>

### CODE REVIEW

**Comment by vpandey-RH** [comment]
@aravindavk  @itisravi @karthik-us  Should we add " background-self-heal-count " option as well ?

**Comment by aravindavk** [comment]
> @aravindavk @itisravi @karthik-us Should we add " background-self-heal-count " option as well ?

Check this PR, this includes all the default values in volfiles. I am not sure why the default value for `background-self-heal-count` is 8, but it is now included in volfile.

**Comment by aravindavk** [comment]
@vpandey-RH, @itisravi, @karthik-us  please review

**Comment by vpandey-RH** [comment]
LGTM.

Tested on a multinode setup as well.

**Comment by aravindavk** [comment]
@itisravi please ack if looks good

**Comment by aravindavk** [comment]
@prashanthpai please review

**Pull request merged**
