### PR TITLE
Downgrade lvm2, disable lvmetad and dmevent in gd2 container

### PR DESCRIPTION
**Pull request by kotreshhr**
Downgrade lvm2 to prevent hangs while using udev.

dmeventd was never designed to be executed inside
'container' so there are some assumption about being
there only single instance of running 'dmeventd' on
the whole host system.

Signed-off-by: Kotresh HR <khiremat@redhat.com>

### CODE REVIEW

**Comment by kotreshhr** [comment]
@Madhu-1 @aravindavk @JohnStrunk @amarts PTAL

**Comment by Madhu-1** [comment]
@nixpanic can you review this PR?

**Comment by Madhu-1** [comment]
add to whitelist

**Comment by Madhu-1** [comment]
https://github.com/gluster/gluster-containers/pull/137 
https://github.com/gluster/gluster-containers/pull/134

**Comment by Madhu-1** [comment]
@SaravanaStorageNetwork can you please review this?

**Comment by SaravanaStorageNetwork** [comment]
Changes looks fine - LGTM

**Pull request merged**
