### PR TITLE
updated peer commands

### LINKED ISSUE #743: Rename peer commands to be consistent
Currently, there are following peer commands in CLI:

`probe <HOSTNAME>`
`detach <HOSTNAME or PeerID>`
`pool list`
`peer status`

This is a mess! We should converge to one common convention:

`peer attach` or `peer add`
`peer detach` or `peer remove`
`peer list`
`peer status`

### PR DESCRIPTION
**Pull request by Madhu-1**
updated peer commands in glustercli 
Closes #743

### CODE REVIEW

**Comment by Madhu-1** [comment]
@prashanthpai  @aravindavk  please review

**Comment by Madhu-1** [comment]
retest this please

**Comment by aravindavk** [comment]
`peer probe` is used from the beginning by the gluster community, I don't see much benefit of changing the command name now.

**Comment by prashanthpai** [comment]
>Ok. we can change to peer add, peer remove and peer list

Sounds good to me :+1: 

@Madhu-1 Please change it to peer add and peer remove

**Comment by Madhu-1** [comment]
@prashanthpai @aravindavk  please review

**Pull request merged**
