### PR TITLE
Fix typo and improve wording in options profile decription

### PR DESCRIPTION
**Pull request by obnoxxx**

### CODE REVIEW

**Comment by obnoxxx** [comment]
Spotten in demo given by @prashanthpai  :-)

**Comment by obnoxxx** [comment]
Added another fix for a typo spotted by @humblec.

**Comment by obnoxxx** [comment]
@rishubhjain oh, I did not check your PR first, sorry for that! I can as well remove my 3rd patch from this PR and we can take yours!

**Comment by rishubhjain** [comment]
@obnoxxx may be its better to keep all the typo correction in one patch. Please continue with this patch.

**Pull request merged**
