### PR TITLE
second part of test infra: test shellscripts

### PR DESCRIPTION
**Pull request by obnoxxx**
This builds on PR #680 and adds a script for testing shell scripts.
It's a separate PR since it has to fix a lot of shell scripts.

### CODE REVIEW

**Comment by kshlm** [comment]
add to whitelist

**Comment by obnoxxx** [comment]
Thanks for merging #680! If it helps, I would be happy to rebase this on top master now.

**Comment by obnoxxx** [comment]
Looking at the centos-ci output, I found that we need to install shellcheck in the centos-ci script in order for the majority of this new test to take effect in CI... I should update this PR with one additional patch.

**Comment by obnoxxx** [comment]
ok. apparently the centos shellcheck is too old ... :-(
Changing the script to not use `-x` for now so centos-ci can pass.

**Comment by obnoxxx** [comment]
finally, the centos-ci run looks completely good :-)

**Pull request merged**
