### PR TITLE
check connectivity to peer before sending join cluster request.

### PR DESCRIPTION
**Pull request by oshankkumar**
Fixes: #1436

Signed-off-by: Oshank Kumar <okumar@redhat.com>

### CODE REVIEW

**Comment by rishubhjain** [comment]
@oshankkumar Thanks for the PR, if possible please add a small e2e test case for peer add failure when peerID is provided instead of peer address (not a priority.).

**Comment by oshankkumar** [comment]
> @oshankkumar please check why we have not received any error while parsing remote address at https://github.com/gluster/glusterd2/blob/master/glusterd2/commands/peers/addpeer.go#L60

we are just splitting host and port, and if port is missing then we set default port in remote address. Since a hostname could be anything not necessarily an IP addr, so it won't return any error even if we pass any random string as the hostname(in this case it is receiving a uuid ).

**Comment by oshankkumar** [comment]
> @oshankkumar Thanks for the PR, if possible please add a small e2e test case for peer add failure when peerID is provided instead of peer address (not a priority.).

@rishubhjain  added test case for this scenario.

**Comment by rishubhjain** [comment]
retest this please

**Pull request merged**
