### PR TITLE
Switch centos-ci to use nightly master RPMs of GlusterFS

### PR DESCRIPTION
**Pull request by kshlm**

### CODE REVIEW

**Comment by prashanthpai** [comment]
@kmlmhnn You will have to port [this change](https://review.gluster.org/#/c/19028/) to glusterfs master branch.

P.S: The CI failure is unrelated.

**Comment by kshlm** [comment]
Looks like something broke from yesterday to today.
`volume start` is causing panics.

**Comment by amarts** [comment]
is it `xlator_api` changes?

**Comment by kshlm** [comment]
> is it xlator_api changes?

Don't think so.

**Comment by atinmu** [comment]
The failure captured from CI output:

```14:48:51 	volume_ops_test.go:42: Using temp dir: /tmp/TestVolume412978160
14:48:51     --- PASS: TestVolume/Create (0.05s)
14:48:51     --- PASS: TestVolume/Expand (0.06s)
14:48:51     --- FAIL: TestVolume/Start (0.09s)
14:48:51     	assertions.go:235: 
                        
	Error Trace:	volume_ops_test.go:119
14:48:51     		
	Error:		Expected nil, but got: &restclient.UnexpectedStatusError{msg:"Unexpected Status", expected:200, actual:500, resp:""}
14:48:51     		
	Messages:	volume start failed```

**Comment by atinmu** [comment]
@kshlm Just curious - is it glusterfs source which is causing this?

**Comment by kshlm** [comment]
@amats It is `xlator_api` changes.

Commit gluster/glusterfs@e65f394a6 updated `protocol/server` to use `xlator_api`. As a part of it, the name of the options struct was changed from `options` to `server_options`. As GD2 hasn't been updated to support `xlator_api` (yet), it isn't able to read-in server xlator options, and the generated volfiles are incomplete. This is causing start to fail.

This commit was merged just yesterday, so I didn't hit any problems while testing yesterday and earlier today as I didn't have the latest master installed.

@prashanthpai we need to speed up the implementation of the `xlator_api` loader. I would like to merge this PR only after that is done. I know it's not really simple, but maybe we could work together to get it faster.

**Comment by prashanthpai** [comment]
> the name of the options struct was changed from options to server_options

Can't we just rename it back ?

**Comment by prashanthpai** [comment]
> Can't we just rename it back ?

Renaming it back errors out and fails to start bricks in glusterd1 itself:

```c
diff --git a/xlators/protocol/server/src/server.c b/xlators/protocol/server/src/server.c
index 7154355e6..158d29c0c 100644
--- a/xlators/protocol/server/src/server.c
+++ b/xlators/protocol/server/src/server.c
@@ -1649,7 +1649,7 @@ struct xlator_dumpops server_dumpops = {
 };
 
 
-struct volume_options server_options[] = {
+struct volume_options options[] = {
         { .key   = {"transport-type"},
           .value = {"rpc", "rpc-over-rdma", "tcp", "socket", "ib-verbs",
                     "unix", "ib-sdp", "tcp/server", "ib-verbs/server", "rdma",
@@ -1845,6 +1845,6 @@ xlator_api_t xlator_api = {
         .dumpops       = &server_dumpops,
         .fops          = &server_fops,
         .cbks          = &server_cbks,
-        .options       = server_options,
+        .options       = options,
         .identifier    = "server-protocol",
 };
```

```log
[2017-12-20 05:15:08.882514] W [MSGID: 101002] [options.c:1257:xlator_option_init_int32] 0-test-server: unknown option: event-threads [Invalid argument]
[2017-12-20 05:15:08.882528] E [MSGID: 101019] [xlator.c:701:xlator_init] 0-test-server: Initialization of volume 'test-server' failed, review your volfile again
[2017-12-20 05:15:08.882534] E [MSGID: 101066] [graph.c:327:glusterfs_graph_init] 0-test-server: initializing translator failed
[2017-12-20 05:15:08.882539] E [MSGID: 101176] [graph.c:698:glusterfs_graph_activate] 0-graph: init failed
[2017-12-20 05:15:08.884391] W [glusterfsd.c:1424:cleanup_and_exit] (-->/usr/local/sbin/glusterfsd(mgmt_getspec_cbk+0x411) [0x40fdaf] -->/usr/local/sbin/glusterfsd(glusterfs_process_volfp+0x1fb) [0x40aa67] -->/usr/local/sbin/glusterfsd(cleanup_and_exit+0x77) [0x4085de] ) 0-: received signum (-1), shutting down
```

**Comment by kshlm** [comment]
@prashanthpai We need to implement support for `xlator_api` sometime. I'd prefer we do it soon.

I had a look around to try and check what we would need to do to implement that support. The way `struct xlator_api` has been layed out with the members we are interested in at the end of the struct, makes it sort of hard for us to implement it well. If the struct members we are interested in were at the beginning of the struct, we could get away with implementing our cgo struct with just those members, and ignoring the rest. But as it is now, we would need to implement all the members till, and whatever they depend on, so that we can reach our members.

I see a few options for solving this.

1. We could just rearrange the `xlator_api` struct, and have all the members we need at the beginning. This will allows us to have a simple cgo struct declaration, that just contains these members. This is the simplest way forward IMO.

2. We could avoid redefining all structs in our seperate cgo header files, and instead depend on the actual header files in libglusterfs. But this will have a build time dependency on GlusterFS for GD2.

3. Pad our redefined struct with the required size at the beginning and whereever needed, so that we reach the first interested member, and implement just the members we need. While this is technically possible, I don't know if we can do this in a portable way.


I would prefer we do 1. @amarts what do you think about this?

@prashanthpai Do you have any other thoughts or comments on this?

**Comment by prashanthpai** [comment]
> If the struct members we are interested in were at the beginning of the struct, we could get away with implementing our cgo struct with just those members, and ignoring the rest.

That is exactly what I intended to do :)

**Comment by amarts** [comment]
I like the idea of moving relevant structures to beginning, but even then, for the long run a complete `xlator_api` may be required.

I suggested to @prashanthpai that for now, he can handle `server_options` differently (like the one for `global_xl_options`), and buy time to implement xlator_api changes properly.

**Comment by prashanthpai** [comment]
> Renaming it back errors out and fails to start bricks in glusterd1 itself:

I looked into this. The options table loaded in `xlator_api.options` for `server.so` was pointing to options tale of `socket.so` (a dependency). With [this change](https://review.gluster.org/#/c/19056/), I'm able to run run CI tests successfully on master.

**Comment by prashanthpai** [comment]
Related PRs: #506 and #507

**Pull request merged**
