### PR TITLE
Make Volume name mandatory in Volume create request

### PR DESCRIPTION
**Pull request by aravindavk**
- CSI driver also passes Volume name to Volume create API
- Mandatory Volume name also helps to ignore
  duplicate(accidental/network failure) Volume create
  API requests(Discussed here
  https://github.com/gluster/glusterd2/issues/919#issuecomment-401022413)
- Applications can generate name and can pass to API, not much benefit
  of auto generating name from glusterd2
- Supporting both the syntax in CLI adds confusion

Signed-off-by: Aravinda VK <avishwan@redhat.com>

### CODE REVIEW

**Comment by atinmu** [comment]
A basic question - as in the legacy case (Heketi + GD1) , volume is created with a convention vol_<UUID> (UUID is generated by heketi and passed to cli/glusterd) , with GCS, who would take up the responsibility of forming up the volume name, is it CSI driver or someone else?

**Comment by aravindavk** [comment]
> A basic question - as in the legacy case (Heketi + GD1) , volume is created with a convention vol_ (UUID is generated by heketi and passed to cli/glusterd) , with GCS, who would take up the responsibility of forming up the volume name, is it CSI driver or someone else?

Name is required field in Volume claim of CSI driver(https://github.com/gluster/gluster-csi-driver/blob/master/pkg/glusterfs/controllerserver.go#L41). CSI driver collects the name from claim and passes it to glusterd2.(Ref: https://github.com/gluster/gluster-csi-driver/blob/master/pkg/glusterfs/controllerserver.go#L94)

**Comment by rishubhjain** [comment]
Fixes https://github.com/gluster/glusterd2/issues/1244

**Comment by aravindavk** [comment]
Since Volume name is required field in CSI driver, whoever calls the CSI driver provides the volume name

**Pull request merged**
