### PR TITLE
Creating meta data for peer

### PR DESCRIPTION
**Pull request by rishubhjain**
Issue https://github.com/gluster/glusterd2/issues/482

### CODE REVIEW

**Comment by rishubhjain** [comment]
@prashanthpai @aravindavk Can you review this PR and check if its as per comments on https://github.com/gluster/glusterd2/pull/541

**Comment by aravindavk** [comment]
How about adding MetaData after peer is successfully joined? After JoinCluster, you will have peerid, Use that peerid and update the metadata in store(All those extra field in RPC can be removed)

**Comment by rishubhjain** [comment]
@aravindavk thanks for the review, yes it can be done, @prashanthpai and I discussed this idea.
@prashanthpai Should I go ahead and make the changes as per aravinda's suggestion?

**Comment by prashanthpai** [comment]
> How about adding MetaData after peer is successfully joined? After JoinCluster, you will have peerid, Use that peerid and update the metadata in store(All those extra field in RPC can be removed)

Sounds good to me. @rishubhjain Please go ahead

**Comment by rishubhjain** [comment]
@aravindavk @prashanthpai I have updated the PR as per your suggestions, Please review.

**Pull request merged**
