### PR TITLE
manpage: Added support for manpage

### PR DESCRIPTION
**Pull request by aravindavk**
Updates: #587
Signed-off-by: Aravinda VK <avishwan@redhat.com>

### CODE REVIEW

**Comment by aravindavk** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
We've been discussing the same thing in Heketi land on and off for a while. I agree that no one in this day and age should have to edit the roff files directly. :-)

Both asciidoc and pandoc are mature and generally have OS packages. md2man seems nice and small(ish) but looks immature to me. Using markdown as the input format has the advantage of being simple and can be displayed directly via tools like github. asciidoc is powerful but has a bit of a unique syntax (IMO).

**Comment by aravindavk** [comment]
> Editing roff files (the man file format) is a PITA.
Maybe we should try a tool like md2man to generate man pages from markdown. Or if we want an already established tools, asciidoc and pandoc have man as a target format.

> If we feel that these tools are too heavy (pandoc in particular) as build requirements, we could just commit the generated man files into the repo along with the markedup text files.

+1

We can also explore generating man page from CLI help message.

**Comment by aravindavk** [comment]
Closing this for now, since this PR only addresses the Makefile related things. Can open new PR once manpage content is available

**Pull request closed without merging**
