### PR TITLE
restclient: Golang REST Client library

### PR DESCRIPTION
**Pull request by aravindavk**
REST Client for Glusterd2 APIs. Initially these APIs will be used by
CLI project, it can be used by any application which is written in Go lang.

Example:

    package main

    import (
        "fmt"
        "github.com/gluster/glusterd2/restclient"
    )

    func main(){
        client := restclient.NewRESTClient("http://localhost:24007", "", "")
        err := client.VolumeStart("gv1")
        if err != nil{
                fmt.Println("Failed to Start Volume gv1")
        } else{
                fmt.Println("Started Volume gv1 successfully")
        }
    }

Signed-off-by: Aravinda VK <mail@aravindavk.in>
Updates: #265

### CODE REVIEW

**Comment by aravindavk** [comment]
Still WIP, yet to add documentation and cover more APIs

**Comment by prashanthpai** [comment]
As we discussed earlier IRL, it would be incredibly useful to create `pkg/api` package containing Request and Response structs. This can be reused internally in core code, in CLI, and in functional tests. It also makes it easy to detect API breakages and also helps to avoid string manipulation for request body.

Your personal repo and branch also needs a rebase :)

**Comment by prashanthpai** [comment]
Also, another usefulside-effect of reusing Request and Reponse structs is that struct validation (basic ones) becomes easy, both at the client and at the server. There are [external go packages](https://github.com/asaskevich/govalidator) that provide this functionality.

**Comment by kshlm** [comment]
@aravindavk Cool! This looks nice.

@ppai's suggestion about having proper request and response types gets a +1 from me too. That should make it easier to later translate the API into a proper spec using OpenAPI or Swagger.

Have you taken a look at either OpenAPI or Swagger?

**Comment by aravindavk** [comment]
Did something wrong again while rebase :(

**Comment by aravindavk** [comment]
Sorry again! submitted new pull request since I messed it up with rebase and edits.

https://github.com/gluster/glusterd2/pull/337

**Pull request closed without merging**
