### PR TITLE
Support ipv6-only hosts

### PR DESCRIPTION
**Pull request by sheenobu**

### CODE REVIEW

**Comment by prashanthpai** [comment]
add to whitelist

**Comment by atinmu** [comment]
LGTM, @prashanthpai @aravindavk any comments?
@sheenobu You'd need to rebase this to master now.

**Comment by prashanthpai** [comment]
@atinmu 

The code changes are straight-forward. But I want to give this a try and test. There may be other places where we have ignored handling ipv6.

**Comment by prashanthpai** [comment]
retest this please

**Comment by sheenobu** [comment]
@prashanthpai  I'm working on an ipv6-only host so I'm sure i'll hit other problems and fix what i can. Thanks!

**Pull request merged**
