### PR TITLE
Removing logging from glustercli

### PR DESCRIPTION
**Pull request by rishubhjain**
https://github.com/gluster/glusterd2/issues/629

### CODE REVIEW

**Comment by rishubhjain** [comment]
Need to resubmit, please don't review

**Comment by rishubhjain** [comment]
@prashanthpai @aravindavk Please review

**Comment by aravindavk** [comment]
> The point was to remove logging to a file. You can still print to stout. Add a "verbose" command line flag. So, do not remove any of the log entries. Log to stdout when verbose option is enabled.

+1

**Comment by rishubhjain** [comment]
@Madhu-1 Is working on this PR.

**Pull request closed without merging**
