### PR TITLE
Tracing: Trace volume expand (add-brick) command.

### LINKED ISSUE #1311: Tracing: Trace volume expand (add-brick) command.
Add instrumentation to trace the volume expand (add-brick) command. Add relevant metadata to the spans like request-id, volume name and the new bricks being added.

### Observed behavior
NA

### Expected/desired behavior
Tracing UI should show the high level steps and the time taken for each of the steps. The top level
span must also show the requestID, volume name and the new bricks being added as part of the request on the tracing UI.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: fedora27
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: source
- Using External ETCD: (yes/no, if yes ETCD version): no
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

### PR DESCRIPTION
**Pull request by sseshasa**
Add instrumentation to trace volume expand transaction. Add relevant
attributes to the trace like request ID, volume name and the bricks being
added to the volume. This is to help in debugging in case the command
fails for some reason. The instrumentation to trace steps of this
transaction is already in place in the common transaction and steps
framework code.

Closes #1311

### CODE REVIEW

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
@sseshasa can you rebase this patch, just want CI to retrigger

**Comment by sseshasa** [comment]
@Madhu-1 Tried rebase but since there are no changes, CI is not getting retriggered.

**Comment by nigelbabu** [comment]
Can you make a cosmetic change?

**Comment by sseshasa** [comment]
@Madhu-1 Okay, I just made minor commit message change. Now it has retriggered.

**Comment by nigelbabu** [comment]
Alright, so the right CI seems to have been triggered

**Pull request merged**
