### PR TITLE
lvm and fs utils code refactor

### PR DESCRIPTION
**Pull request by aravindavk**
Moved lvm related functions from `$SRC/glusterd2/snapshot/lvm`
and `$SRC/plugins/device/deviceutils/` to `$SRC/pkg/lvmutils`

Also moved fs related functions from `plugins/deviceutils` to
`$SRC/pkg/fsutils`.

Fixes: #1187
Signed-off-by: Aravinda VK <avishwan@redhat.com>

### CODE REVIEW

**Comment by aravindavk** [comment]
I will rebase this PR once volume expand PR(https://github.com/gluster/glusterd2/pull/1281) merges(To move volume expand related functions)

**Comment by aravindavk** [comment]
Included lvextend functions in `pkg/lvmutils`. @Madhu-1 please review

**Comment by Madhu-1** [comment]
@aravindavk CI failure

```
14:19:23 # github.com/gluster/glusterd2/e2e
14:19:23 e2e/smartvol_ops_test.go:67:25: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:81:26: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:111:25: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:124:26: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:155:25: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:169:26: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:231:25: undefined: deviceutils
14:19:23 e2e/smartvol_ops_test.go:245:26: undefined: deviceutils
```

**Comment by aravindavk** [comment]
tests passing now.

**Pull request merged**
