### PR TITLE
e2e: Remove arbitrary sleeps in peer operation test

### PR DESCRIPTION
**Pull request by prashanthpai**
Now that e2e tests use external etcd, we no longer need the sleeps
that were added as a workaround for elasticetcd (embedded etcd) issue.

This change will shave 12 seconds off the time it takes to run e2e
tests.

~~Let's see if the CentOS CI test passes with this change.~~

Related PR https://github.com/gluster/glusterd2/pull/970
Signed-off-by: Prashanth Pai <ppai@redhat.com>

### CODE REVIEW

**Comment by prashanthpai** [comment]
> @prashanthpai, I have a question, removing sleep will work with and without external ETCD in e2e.

On my laptop, it almost never passes with elasticetcd. I don't know about the centos CI. I'm really not in favour of:
```
if external etcd {
    don't sleep
}
```

**Comment by Madhu-1** [comment]
@prashanthpai  but as long as we support elastic ETCD for e2e, test cases should pass in both scenarios.
IMO,  removing sleep may affect running e2e with elastic ETCD.

**Comment by Madhu-1** [comment]
@prashanthpai  AFAIK we have a flag in e2e to enable and disable external ETCD.
```
-external-etcd=false
```

**Comment by prashanthpai** [comment]
> @prashanthpai AFAIK we have a flag in e2e to enable and disable external ETCD.

I know :)

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
> Whenever we bring back elasticetcd as the default, we should have fixed the need for having these sleeps.

Agreed. I had thought about https://github.com/gluster/glusterd2/issues/1113 too and I think it will help fix some of embedded etcd issues, as a side effect.

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
retest this please

**Pull request merged**
