### PR TITLE
volgen: add sdfs in volfile

### PR DESCRIPTION
**Pull request by amarts**
dentry serialize translator is required in brick path to reduce the issues with parallel renames and lookups.

updates gluster/glusterfs#421

Signed-off-by: Amar Tumballi <amarts@redhat.com>

### CODE REVIEW

**Comment by amarts** [comment]
This needs https://review.gluster.org/19866 to be merged to have an option to enable / disable. But no harm in having it present regardless in CI/CD tests.

**Comment by aravindavk** [comment]
A gofmt related issue.

> 06:54:51 ./glusterd2/volgen2/volfile_brick.go does not conform to gofmt rules. Run: gofmt -s -w ./glusterd2/volgen2/volfile_brick.go
> 06:54:55 make: *** [verify] Error 1

**Comment by amarts** [comment]
The same passes in my laptop.. is there a spefic config i have to give for gofmt?

**Comment by prashanthpai** [comment]
@amarts Running `gofmt -s -w ./glusterd2/volgen2/volfile_brick.go` will fix the format automatically.

Usually go developers have running `gofmt` integrated with text editor like vim and gets run on saving the file.

**Pull request merged**
