### PR TITLE
Fix capitalized error message format.

### PR DESCRIPTION
**Pull request by imjoey**
As mentioned in the error-handling section of [coding conventions](https://github.com/gluster/glusterd2/blob/master/doc/coding.md#error-handling) below:
```
* Error strings should not start with a capital letter.
```
This pull request does what #902 have done that set the first letter of error message to lowercase. Note that the names of struct definitions are already ignored, such as `BrickType`, etc.

Signed-off-by: imjoey <majunjiev@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
ok to test

**Comment by Madhu-1** [comment]
add to whitelist

**Comment by Madhu-1** [comment]
@aravindavk can you trigger centos CI?

**Comment by prashanthpai** [comment]
add to whitelist

**Comment by imjoey** [comment]
@Madhu-1 @prashanthpai , thanks a lot. ^_^ .

**Pull request merged**
