### PR TITLE
Get ready for 4.1.0 tagging

### PR DESCRIPTION
**Pull request by kshlm**

### CODE REVIEW

**Comment by kshlm** [comment]
@prashanthpai Could you please merge this? I made a mess with the rc0 release, trying to push it myself. This time no shortcuts.

Also, are there any other PRs that you want in the release?

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
retest this please

**Comment by prashanthpai** [comment]
retest this please

**Pull request merged**
