### PR TITLE
Kill old glusterfsds post multiplexing

### PR DESCRIPTION
**Pull request by vpandey-RH**
Fixes - [#1403](https://github.com/gluster/glusterd2/issues/1403)

ISSUE - Force start doesn't kill bricks and respawn but only spawns killed ones,
so in case when we set multiplex as on and then do a force start on volume,
the old glusterfsds are still running.

Fix - Look for an already running glusterfsd for the brick to be multiplexed and terminate its glusterfsd
only after a target brick for currrent brick (brick to be multiplexed) has been found.

Signed-off-by: Vishal Pandey <vpandey@redhat.com>

### CODE REVIEW

**Comment by vpandey-RH** [comment]
retest this please

**Comment by aravindavk** [comment]
> Fix - Look for an already running glusterfsd for the brick to be multiplexed and terminate its glusterfsd
only after a target brick for currrent brick (brick to be multiplexed) has been found.

As discussed here https://github.com/gluster/glusterd2/issues/1405#issuecomment-447262010, Volume availability will get affected if running bricks are stopped and restarted.

**Comment by vpandey-RH** [comment]
@aravindavk In this case we will be asking the brick to continue working through the glusterfsd that it will be multiplexed into, so its old glusterfsd will not be of any use. If we keep on running the old glusterfsds there could be a case where 1000 glusterfsds are running at one point in time on large setups.

**Comment by atinmu** [comment]
@vpandey-RH Please abandon this PR as discussed earlier.

**Pull request closed without merging**
