### PR TITLE
volume-options: dont start daemons if volume state is  stopped or created

### PR DESCRIPTION
**Pull request by Madhu-1**
Allow to set options on volumes if volume state is stopped or created, don't start daemons.
if volume state is started then set options on volume and also start daemons.

Fixes: #934 

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@prashanthpai @aravindavk @rishubhjain please review.

**Comment by aravindavk** [comment]
Note: This will cause problem without #923 for some daemons which requires restart like Quotad.

    Start Volume 1
    Set Quota for Volume 1
    Start Volume 2
    Set Quota for Volume 2
    Stop Volume 2
    Reset Quota for Volume 2

Quotad will not be restarted after last restart because of the state Check.

**Comment by Madhu-1** [comment]
once this is merged, I will send PR to #923

**Comment by aravindavk** [comment]
@prashanthpai any comments to this PR?

**Pull request merged**
