### PR TITLE
Add logging if there is an error in CLI

### LINKED ISSUE #1414: log error message for volume create validation in CLI
### Observed behavior
currently, we are not logging the error message if there is a validation failure in glustercli
### Expected/desired behavior
in glustercli user should be able to see the detailed error message with `-v` logs.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

### PR DESCRIPTION
**Pull request by Madhu-1**
add logging if there is an error in CLI, with the help of `-v` flag user should
be able to check the failure logs.

Fixes #1414
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by atinmu** [comment]
@Madhu-1 Is this the only set of API(s) where we're missing these logs?

**Comment by Madhu-1** [comment]
@atinmu added missing logs , PTAL

**Comment by Madhu-1** [comment]
retest this please

**Comment by Madhu-1** [comment]
@aravindavk PTAL

**Pull request merged**
