### PR TITLE
updated endpoints for geo replication and volumereset 

### PR DESCRIPTION
**Pull request by Madhu-1**
updated endpoints for geo-replication and volume reset with Request and Response type

### CODE REVIEW

**Comment by Madhu-1** [comment]
@prashanthpai  please review

**Comment by prashanthpai** [comment]
@Madhu-1 Add a reference to the issue you are fixing in the PR. For example `Closes #<issue-number>` if it fully fixes the issue or `Updates #<issue-number>` if it partially fixes it.

**Comment by prashanthpai** [comment]
retest this please

**Comment by Madhu-1** [comment]
Updates #584

**Comment by prashanthpai** [comment]
Leaving a note here: As pointed out by @Madhu-1 , links to `godoc` for types belonging to plugins are broken and it requires changes to `pkg/tools/generate-doc.go` and shall be fixed later.

**Pull request merged**
