### PR TITLE
Fix mistaken command flag descriptions

### PR DESCRIPTION
**Pull request by imjoey**
The descriptions of the `--etcdcurls` and `--etcdpurls` flags are reversely assigned.

### CODE REVIEW

**Comment by aravindavk** [comment]
add to whitelist

**Comment by imjoey** [comment]
cc @prashanthpai @Madhu-1, would you please help me trigger the centos-ci . Thanks in advance.

**Comment by rishubhjain** [comment]
retest this please

**Comment by imjoey** [comment]
Thanks a lot, @rishubhjain . I just find that there has a prompt `Only reviews by reviewers with write access count toward mergeability` on your approval of this change. Does it matter?

**Comment by rishubhjain** [comment]
Ya, so  a patch can be merged only if it has been approved by someone who has write accesss to this repo. So Aravinda has already approved your patch, so it can be merged.

**Comment by aravindavk** [comment]
We are working on the fix to our CI system. Only one ci job should vote.

Your PR will get merged once that CI issue gets fixed.

**Comment by imjoey** [comment]
hi @aravindavk , got it. Thanks a lot. I'm new here so I just want to confirm it's not due to my fault, there is no rush. 😄

**Comment by atinmu** [comment]
@imjoey We value all the contributions, no matter in what form it comes. Thanks for your first patch in this repo. Please keep contributing :+1:

**Comment by imjoey** [comment]
hi, @atinmu,  😄 Surely I will. Thank you guys for the great work.

**Pull request merged**
